### ISSUE TITLE
PID

### ISSUE THREAD

**Issue by thomas32426** [ksu-ground-vehicle/tasks#6]
Set up the PID for the ground vehicle motors.

**Comment by stoplime** [comment]
The PIDs requires planning on how the drive control will be set up. The main input and output of the PIDs should also be discussed and designed before implementation.  If the Input is the current position and the target position, there are some concerns about the vehicle being able to traverse the course correctly. The output I would presume should also be a PID output control for two motors, but I would like a conformation with the design of the vehicle.

**Comment by john55w** [comment]
The input of the PID controller should be an angle,  which is the angular difference between the heading of the vehicle and the current path to the target location.  The key component is having a path already created using ORBSLAM2, and path updates if necessary from LIDAR detection of obstacles,   that path will be compared with our heading to get the angular error input for our PID control
